package com.CST8319.canadianfitnesstracker.database;

public class WorkoutData {
    public static final String[][] WORKOUTS = {
            {"Running", "Cardio exercise involving continuous running."},
            {"Walking", "Low impact cardio activity done at a steady pace."},
            {"Cycling", "Cardio workout using a bicycle."},
            {"Swimming", "Full body cardio exercise performed in water."},
            {"Jump Rope", "Cardio workout involving repeated rope jumps."},
            {"Rowing", "Full body cardio exercise using a rowing motion."},
            {"Elliptical", "Low impact cardio machine workout."},
            {"Stair Climbing", "Cardio workout using stairs or a stair machine."},
            {"Hiking", "Walking long distances over natural terrain."},
            {"Sprinting", "High intensity running for short distances."},
            {"Push Ups", "Bodyweight exercise targeting chest and arms."},
            {"Pull Ups", "Upper body exercise lifting the body with arms."},
            {"Squats", "Lower body exercise targeting legs and glutes."},
            {"Lunges", "Leg exercise stepping forward and lowering body."},
            {"Plank", "Core exercise holding the body in a straight position."},
            {"Burpees", "Full body exercise combining squat, jump, and pushup."},
            {"Mountain Climbers", "Cardio core exercise in plank position."},
            {"Sit Ups", "Core exercise raising the torso from the floor."},
            {"Crunches", "Abdominal exercise lifting shoulders off ground."},
            {"Leg Raises", "Core exercise lifting legs while lying down."},
            {"Bench Press", "Strength exercise pressing weight from chest."},
            {"Deadlift", "Full body strength exercise lifting weight from floor."},
            {"Shoulder Press", "Upper body exercise pressing weight overhead."},
            {"Bicep Curl", "Arm exercise bending the elbow with weight."},
            {"Tricep Extension", "Arm exercise targeting triceps."},
            {"Lat Pulldown", "Back exercise pulling bar downward."},
            {"Chest Fly", "Chest exercise moving arms inward with weight."},
            {"Leg Press", "Machine exercise pushing weight with legs."},
            {"Calf Raises", "Lower leg exercise lifting heels."},
            {"Front Squat", "Squat variation holding weight in front."},
            {"Basketball", "Team sport involving shooting a ball into a hoop."},
            {"Soccer", "Team sport where players kick a ball into a goal."},
            {"Tennis", "Racket sport played against an opponent."},
            {"Volleyball", "Team sport hitting a ball over a net."},
            {"Baseball", "Bat and ball sport played between two teams."},
            {"Softball", "Variant of baseball played with a larger ball."},
            {"Football", "Team sport involving passing and running plays."},
            {"Hockey", "Sport played by hitting a puck into a goal."},
            {"Golf", "Precision sport hitting a ball into holes."},
            {"Badminton", "Racket sport played with a shuttlecock."},
            {"Yoga", "Flexibility and balance exercises with controlled breathing."},
            {"Pilates", "Core strength and flexibility training."},
            {"Stretching", "Exercises designed to improve flexibility."},
            {"Meditation", "Mindfulness practice often combined with light movement."},
            {"Dance Fitness", "Cardio workout performed through dance."},
            {"Zumba", "Dance-based aerobic fitness workout."},
            {"Kickboxing", "Cardio workout combining punches and kicks."},
            {"CrossFit", "High intensity functional training program."},
            {"HIIT", "High intensity interval training workout."},
            {"Circuit Training", "Workout rotating through multiple exercises."}
    };
}
